targets:
  - name: Translations
    sources:
      - manifest.json
    file: /languages/%two_letters_code%/manifest.json
    format: xliff
files:
  - source: /*.json
    translation: /languages/%two_letters_code%/%original_file_name%
