name: Build a ZIP and MCPACK version and publish to CurseForge

on:
  push
  
jobs:
 build:
    runs-on: ubuntu-latest
    steps:   
     - name: Clone repository
       uses: actions/checkout@v3
    
     - name: Create report file
       run: date +%s > report.txt
    
     - name: Set variables
       run: |
         cp "information.txt" tmp.txt
         sed -i '2d' information.txt
         VERSION=$(sed 's/version: //g' information.txt)
         cp "tmp.txt" information.txt
         sed -i '1d' information.txt
         ISDONE=$(sed 's/done: //g' information.txt)
         rm information.txt tmp.txt
         echo "VERSION=$VERSION" >> $GITHUB_ENV
         echo "ISDONE=$ISDONE" >> $GITHUB_ENV
     - name: Build ZIP
       uses: thedoctor0/zip-release@master
       with:
         type: 'zip'
         filename: 'MCPE-Lunar-Client-Crosshair_latest.zip'
         exclusions: '*.git* ./build/ README.md report.txt'

     - name: Move to "build" directory
       run: mv ./MCPE-Lunar-Client-Crosshair_latest.zip ./build/
       shell: bash

     - name: Build .MCPACK
       run: cp ./build/MCPE-Lunar-Client-Crosshair_latest.zip ./build/MCPE-Lunar-Client-Crosshair_latest.mcpack
       shell: bash
       
     - name: Upload MCPE LC Crosshair ZIP Build Artifact
       uses: actions/upload-artifact@v2
       with:
         name: MCPE-Lunar-Client-Crosshair_latest.zip
         path: ./build/MCPE-Lunar-Client-Crosshair_latest.zip
         
     - name: Upload MCPE LC Crosshair MCPACK Build Artifact
       uses: actions/upload-artifact@v2
       with:
         name: MCPE-Lunar-Client-Crosshair_latest.mcpack
         path: ./build/MCPE-Lunar-Client-Crosshair_latest.mcpack
     
     - name: Commit report
       run: |
          git config --global user.name '${{ secrets.git_username }}'
          git config --global user.email '${{ secrets.git_email }}'
          git init
          git add -A
          git commit -am "Made new build"
          git push -u origin ${{ github.ref_name }}
     - name: Rename ZIP and MCPACK file
       run: |
         mv "MCPE-Lunar-Client-Crosshair_latest.zip" MCPE-Lunar-Client-Crosshair_$VERSION.zip 
         mv "MCPE-Lunar-Client-Crosshair_latest.mcpack" MCPE-Lunar-Client-Crosshair_$VERSION.mcpack 
       
 publish: 
    needs: build
    runs-on: ubuntu-latest
    steps:
     - name: Clone repository
       uses: actions/checkout@v3
       
     - name: "Upload to CurseForge"
       uses: itsmeow/curseforge-upload@v3
       with:
          file_path: "./build/MCPE-Lunar-Client-Crosshair_${{ env.VERSION }}.mcpack"
          game_endpoint: "minecraft-bedrock"
          relations: ""
          game_versions: ""
          project_id: "641472"
          token: "${{ secrets.CF_API_TOKEN }}"
       if: (env.ISDONE == 'true') && (github.ref_name == 'main')
