name: Build a ZIP and MCPACK version

on:
  push:
  pull_request:

jobs:
 build:
    runs-on: ubuntu-latest
    steps:   
     - uses: actions/checkout@v4
    
     - name: Build ZIP
       uses: thedoctor0/zip-release@master
       with:
         type: 'zip'
         filename: 'MCPE-Lunar-Client-Crosshair_${{ github.ref_name }}.zip'
         exclusions: '*.git* ./build/ README.md report.txt'

     - name: Build .MCPACK
       run: cp MCPE-Lunar-Client-Crosshair_${{ github.ref_name }}.zip MCPE-Lunar-Client-Crosshair_${{ github.ref_name }}.mcpack
       
     - name: Upload MCPE LC Crosshair Build Artifacts
       uses: actions/upload-artifact@v4
       with:
         name: MCPE Lunar Client Crosshair
         path: |
           MCPE-Lunar-Client-Crosshair_${{ github.ref_name }}.zip
           MCPE-Lunar-Client-Crosshair_${{ github.ref_name }}.mcpack
